### ISSUE TITLE
Transfer tx id 

### ISSUE THREAD

**Issue by gavlnxu** [smirkcat/tron-rpc#1]
https://github.com/smirkcat/tron-rpc/blob/master/service/client.go#L292

这里的txid经过hex后怎么在区块链浏览器查询不到,转账后应该用什么字段去查询?

**Comment by smirkcat** [comment]
这里txid就是直接结果了 https://github.com/smirkcat/tron-rpc/blob/master/service/client.go#L314 直接就用这个查询呀 如果转账错误那肯定查询不到

**Comment by smirkcat** [comment]
@gavlnxu  如果没有疑问我就关闭这个问题
