### ISSUE TITLE
遇到两个问题，麻烦指点一下

### ISSUE THREAD

**Issue by janjanEnjoy** [smirkcat/tron-rpc#2]
1、ref_block_bytes，从block_header中获取到高度，没有8个字节呀，如：13802595，要如何截取Bytes[6:8]呢
2、tx_id得到正确，使用对应地址私钥sign签名，获得了签名结果，但是为什么只有前32个字节正确？

**Comment by smirkcat** [comment]
1. 这个代码自动转换的，我直接用的GetNodeInfo 这个方法调用返回的，自动解析的，你说的这个时间有点久了，我不知道你说的这个
2. 至于签名，签名本来就是调用这个函数 https://github.com/smirkcat/tron-rpc/blob/master/util/transaction.go#L14-L32 ，我目前没出过错
3. 建议你详细看看代码，我觉得你还没有看懂代码

**Comment by janjanEnjoy** [comment]
> 1. 这个代码自动转换的，我直接用的GetNodeInfo 这个方法调用返回的，自动解析的，你说的这个时间有点久了，我不知道你说的这个
> 2. 至于签名，签名本来就是调用这个函数 https://github.com/smirkcat/tron-rpc/blob/master/util/transaction.go#L14-L32 ，我目前没出过错
> 3. 建议你详细看看代码，我觉得你还没有看懂代码

嗯，我再试试。感谢大佬解答

**Comment by smirkcat** [comment]
看了代码 https://github.com/smirkcat/tron-rpc/blob/master/trx/transcation.go#L75 这个地方获取的高度

**Comment by janjanEnjoy** [comment]
![image](https://user-images.githubusercontent.com/31478775/115662916-45591f80-a372-11eb-9094-4f7353b13a8e.png)因为是准备本地构建交易和离线签名，您代码里获取的高度也只有3个字节，比如blockHeight:13802595, 对应 hex "639cd20000000000",  所以这里应该 取[1,3]：“9cd2”作为 ref_block_bytes 参数这样吗？
然后，签名广播了这个交易的话，这个交易也会上链发布在13802595这个区块吗？我不是太懂它的协议原理。
我看到您也是本地部署了他的rpc服务，然后请求接口来的，也许我后面也会采用这种形式，
非常感谢您一直的回复和帮助。

**Comment by janjanEnjoy** [comment]
已经处理好了，大小端的问题，ohyeah

**Comment by smirkcat** [comment]
grpc只是一种协议调用 ，你需要去了解这个协议原理哈，至于广播交易没有发布区块得概念哈，我觉着你很多基础都不明白，你还是去看下来，这个我没法给你回答，不在本项目讨论范围内

**Comment by janjanEnjoy** [comment]
> grpc只是一种协议调用 ，你需要去了解这个协议原理哈，至于广播交易没有发布区块得概念哈，我觉着你很多基础都不明白，你还是去看下来，这个我没法给你回答，不在本项目讨论范围内
嗯，我再理解一下
