### ISSUE TITLE
protoc 执行报错

### ISSUE THREAD

**Issue by DukeDeng** [smirkcat/tron-rpc#8]
core/contract/smart_contract.proto:9:1: warning: Import core/Tron.proto is unused.

**Comment by DukeDeng** [comment]
屏蔽代码后，执行，生成的*.pb文件加载到了新建的github.com/tronprotocol/* 文件夹下

**Comment by smirkcat** [comment]
哦，这里手动修改了生成的代码的 他自动github.com/tronprotocol/  core 和 api  目录下, 至于为什么在这个目录下，是因为官方的proto文件是这么写的哈，这个需要你要去了解grpc相关知识，这里我不在过多叙述。
生成代码之后我把 core api 这两个目录移动到了项目根目录下面，然后我修改api目录下面那两个文件 引入的包 core "github.com/tronprotocol/grpc-gateway/core" 为   core "tron/core"
